services:
    server:
        build: ../Part5
        container_name: server
    proxy-nginx:
        build: .
        container_name: proxy
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf